project:
  type: website
<<<<<<< HEAD

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
=======
  output-dir: docs

website:
  title: "Multivariate (PSY 5246C) - Fall 2023"
  sidebar:
    logo: "mult2023.png"
    pinned: true
    align: center
>>>>>>> 177986d (first commit)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

<<<<<<< HEAD


=======
editor: visual
>>>>>>> 177986d (first commit)
