---
title: "Multivariate (PSY 5246C) - Fall 2023"
---

Syllabus: [HTML](files/Multivariate syllabus Fall 2023.html) [PDF](files/Multivariate-syllabus-Fall-2023.pdf)

[Lecture videos on Youtube](https://www.youtube.com/playlist?list=PLKrGRYggZL-Hk59tYcUX-kS10OAQOQjmp)

| Week | Topic                   | HTML slides | PDF handout |
|------|-------------------------|-------------|-------------|
| 1    | Matrix algebra          | [Mult23-1.html](files/Mult23-1.html) | [Mult23-1.pdf](files/Mult23-1.pdf) |
| 2    | Linear regression       | [Mult23-2.html](files/Mult23-2.html) | [Mult23-2.pdf](files/Mult23-2.pdf) |
| 3    | Linear regression       | [Mult23-3.html](files/Mult23-3.html) | [Mult23-3.pdf](files/Mult23-3.pdf) |
| 4    | Logistic regression       | [Mult23-4.html](files/Mult23-4.html) | [Mult23-4.pdf](files/Mult23-4.pdf) |
| 5    | Poisson regression        | [Mult23-5.html](files/Mult23-5.html) | [Mult23-5.pdf](files/Mult23-5.pdf) |
| 6    | Matrix algebra 2          | [Mult23-6.html](files/Mult23-6.html) | [Mult23-6.pdf](files/Mult23-6.pdf) |
| 7    | Principal components analysis | [Mult23-7.html](files/Mult23-7.html) | [Mult23-7.pdf](files/Mult23-7.pdf) | 
| 8    | Factor analysis           | [Mult23-8.html](files/Mult23-8.html) | [Mult23-8.pdf](files/Mult23-8.pdf) |
| LCA  | Latent class analysis     | [Mult23-LCA.html](files/Mult23-LCA.html) | [Mult23-LCA.pdf](files/Mult23-LCA.pdf) |
| 9    | MANOVA & RM ANOVA         | [Mult23-9.html](files/Mult23-9.html) | [Mult23-9.pdf](files/Mult23-9.pdf) |
| 10   | Mixed models              | [Mult23-10.html](files/Mult23-10.html) | [Mult23-10.pdf](files/Mult23-10.pdf) |